engines:
  shellcheck:
    enabled: true
    checks:
      SC1008:
        enabled: false
  markdownlint:
    enabled: true
    checks:
      MD010:
        enabled: false

ratings:
  paths:
  - "doc/**.md"
  - "**.sh"
  - "workshop"
