sudo: required
before_install:
  - eval "$DEPS"
script:
  - $SHELL workshop posit.sh run .
matrix:
  include:
    - env: SHELL="dash" DEPS=":"
      os:  linux

    - env: SHELL="bash" DEPS=":"
      os:  linux

    - env: SHELL="bash" DEPS=":"
      os:  osx

    - env: SHELL="posh" DEPS="sudo apt-get -qq update ; sudo apt-get install -y posh"
      os:  linux

    - env: SHELL="mksh" DEPS="sudo apt-get -qq update ; sudo apt-get install -y mksh"
      os:  linux

    - env: SHELL="zsh" DEPS="sudo apt-get -qq update ; sudo apt-get install -y zsh"
      os:  linux

    - env: SHELL="pdksh" DEPS="sudo apt-get -qq update ; sudo apt-get install -y pdksh"
      os:  linux

    - env: SHELL="yash" DEPS="sudo apt-get -qq update ; sudo apt-get install -y yash"
      os:  linux

    - env: SHELL="ksh" DEPS="sudo apt-get -qq update ; sudo apt-get install -y ksh"
      os:  linux

    - env: SHELL="zsh-beta" DEPS="sudo apt-get -qq update ; sudo apt-get install -y zsh-beta"
      os:  linux

    - env: SHELL="zsh" DEPS="brew update ; brew install zsh"
      os:  osx

    - env: SHELL="ksh" DEPS="brew update ; brew install ksh"
      os:  osx

    - env: SHELL="mksh" DEPS="brew update ; brew install mksh"
      os:  osx
