sudo: required
before_install:
  - ${APTKEY:+sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys "$APTKEY"}
  - ${PPA:+echo "deb http://ppa.launchpad.net/${PPA}/ubuntu main" | sudo tee -a "/etc/apt/sources.list"}
  - ${APTGET:+sudo apt-get update}
  - ${APTGET:+sudo apt-get install -y ${APTGET}}
  - ${BREW:+brew update}
  - ${BREW:+brew install  ${BREW}}
script:
  - $SHELL workshop posit run .
matrix:
  include:
    - env: SHELL="dash" APTGET=""
      os:  linux

    - env: SHELL="bash" APTGET=""
      os:  linux

    - env: SHELL="bash" APTGET=""
      os:  osx

    - env: SHELL="posh" APTGET="posh"
      os:  linux

    - env: SHELL="mksh" APTGET="mksh"
      os:  linux

    - env: SHELL="zsh" APTGET="zsh"
      os:  linux

    - env: SHELL="pdksh" APTGET="pdksh"
      os:  linux

    - env: SHELL="yash" APTGET="yash"
      os:  linux

    - env: SHELL="ksh" APTGET="ksh"
      os:  linux

    - env: SHELL="zsh-beta" APTGET="zsh-beta"
      os:  linux

    - env: SHELL="zsh" BREW="zsh"
      os:  osx

    - env: SHELL="ksh" BREW="ksh"
      os:  osx

    - env: SHELL="mksh" BREW="mksh"
      os:  osx

    - env: SHELL="dash" BREW="dash"
      os:  osx

    - env: SHELL="bash2.05b" APTGET="bash2.05b" PPA="agriffis/bashes precise" APTKEY="F5751EC8"
      os:  linux

    - env: SHELL="bash3.0.16" APTGET="bash3.0.16" PPA="agriffis/bashes precise" APTKEY="F5751EC8"
      os:  linux

    - env: SHELL="bash3.2.48" APTGET="bash3.2.48" PPA="agriffis/bashes precise" APTKEY="F5751EC8"
      os:  linux

    - env: SHELL="bash4.2.45" APTGET="bash4.2.45" PPA="agriffis/bashes precise" APTKEY="F5751EC8"
      os:  linux
