sudo: required
before_install:
  - eval "${APTGET:+sudo apt-get -qq update ; sudo apt-get install -y ${APTGET}}"
  - eval "${BREW:+brew update ; brew install  ${BREW}}"
script:
  - $SHELL workshop posit run .
matrix:
  include:
    - env: SHELL="dash" APTGET=""
      os:  linux

    - env: SHELL="bash" APTGET=""
      os:  linux

    - env: SHELL="bash" APTGET=""
      os:  osx

    - env: SHELL="posh" APTGET="posh"
      os:  linux

    - env: SHELL="mksh" APTGET="mksh"
      os:  linux

    - env: SHELL="zsh" APTGET="zsh"
      os:  linux

    - env: SHELL="pdksh" APTGET="pdksh"
      os:  linux

    - env: SHELL="yash" APTGET="yash"
      os:  linux

    - env: SHELL="ksh" APTGET="ksh"
      os:  linux

    - env: SHELL="zsh-beta" APTGET="zsh-beta"
      os:  linux

    - env: SHELL="zsh" BREW="zsh"
      os:  osx

    - env: SHELL="ksh" BREW="ksh"
      os:  osx

    - env: SHELL="mksh" BREW="mksh"
      os:  osx
