sudo: required
before_install:
  # Install PPA if environment requires it
  - ${PPA:+sudo add-apt-repository ppa:${PPA} -y}

  # Update apt catalogue if going to install anything
  - ${APTGET:+sudo apt-get update}

  # Install required apt packages
  - ${APTGET:+sudo apt-get install -y ${APTGET}}

  # Update brew catalogue if going to install anything
  - ${BREW:+brew update}

  # Install brew dependencies
  - ${BREW:+brew install ${BREW}}

script:
  - posit_shell=${posit_shell} $posit_shell lib/workshop.sh posit run doc/testing.md
matrix:
  include:
    - env: posit_shell="dash" APTGET=""
      os:  linux

    - env: posit_shell="bash" APTGET=""
      os:  linux

    - env: posit_shell="bash" APTGET=""
      os:  osx

    - env: posit_shell="posh" APTGET="posh"
      os:  linux

    - env: posit_shell="mksh" APTGET="mksh"
      os:  linux

    - env: posit_shell="zsh" APTGET="zsh"
      os:  linux

    - env: posit_shell="pdksh" APTGET="pdksh"
      os:  linux

    - env: posit_shell="yash" APTGET="yash"
      os:  linux

    - env: posit_shell="ksh" APTGET="ksh"
      os:  linux

    - env: posit_shell="zsh-beta" APTGET="zsh-beta"
      os:  linux

    - env: posit_shell="busybox sh" APTGET="busybox"
      os:  linux

    - env: posit_shell="zsh" BREW="zsh"
      os:  osx

    - env: posit_shell="ksh" BREW="ksh"
      os:  osx

    - env: posit_shell="mksh" BREW="mksh"
      os:  osx

    - env: posit_shell="dash" BREW="dash"
      os:  osx

    - env: posit_shell="bash2.05b" APTGET="bash2.05b" PPA="agriffis/bashes"
      os:  linux

    - env: posit_shell="bash3.0.16" APTGET="bash3.0.16" PPA="agriffis/bashes"
      os:  linux

    - env: posit_shell="bash3.2.48" APTGET="bash3.2.48" PPA="agriffis/bashes"
      os:  linux

    - env: posit_shell="bash4.2.45" APTGET="bash4.2.45" PPA="agriffis/bashes"
      os:  linux
