version: "0.0.{build}"
os: Windows Server 2012 R2
build: off
deploy: off

environment:
  matrix:
    - SHELL: bash
    - SHELL: dash
    - SHELL: mksh
    - SHELL: ksh

install:
  - cmd: C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - cmd: C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy"
  - cmd: C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S $SHELL"

test_script:
  - cmd: C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER; $SHELL workshop posit run ."
