version: "0.0.{build}"
os: Windows Server 2012 R2
build: off
deploy: off

test_script:
  - cmd: call %SHELLENV% -lc "cd $APPVEYOR_BUILD_FOLDER; sh lib/workshop.sh posit run doc/matrix.md"

environment:
  matrix:
    - SHELLENV: C:\msys64\usr\bin\bash
    - SHELLENV: C:\MinGW\msys\1.0\bin\sh
