version: "0.0.{build}"
os: Windows Server 2012 R2
build: off
deploy: off

environment:
  matrix:
    - SHELL: bash
    - SHELL: dash
    - SHELL: mksh
    - SHELL: ksh

install:
  - cmd: bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - cmd: bash -lc "pacman --noconfirm -Sy"
  - cmd: bash -lc "pacman --noconfirm -S $SHELL"

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmd: bash -lc "$SHELL workshop posit run ."
