#!/usr/bin/env sh

workshop ()
{
	test "${#}" -gt 1 || return 0
	_executable="${1:-}"
	_executable_dir="$(dirname "${workshop_executable:-$_executable}")"
	_input="${2##*-}"
	_input="${_input##*-}"
	_main="$(basename "${_input}")"
	_master="https://raw.githubusercontent.com/alganet/workshop/master/"
	_server="${workshop_server:-${_master}}"
	shift 2

	set -euf
	unsetopt NO_MATCH  >/dev/null 2>&1 || :
	setopt SHWORDSPLIT >/dev/null 2>&1 || :

	_modules="${workshop_modules:- : workshop }"
	_dependencies="${workshop_modules:-}${workshop_modules:+ }${_main}"

	test ! -z "${_dependencies}" || return 0

	while true 'Dependency Loop'
	do
		for _dependency in ${_dependencies}
		do
			_dependency_status='ok'

			for _dependency_check in ${_dependencies}
			do
				if test "${_modules#*$_dependency_check}" != "$_modules"
				then
					if test "${_dependency_status}" = 'ok'
					then
						continue
					fi
				else
						_dependency_status="${_dependency_check} missed"
				fi
			done

			if test "${_dependency_status}" = 'ok'
			then
				break 2 # Back to 'Dependency Loop'
			fi

			if test "${_modules#*$_dependency}" != "$_modules"
			then
				continue
			fi

			_found_module=''
			_ifs="${IFS}"
			IFS="${workshop_path_separator:-:}"
			for _part in ${workshop_path:-${PWD}:${_executable_dir}}
			do
				_file="$(echo "${_part}/${_dependency}")"

				if test -f "${_file}"
				then
					_found_module="${_file}"
					break # Back to for _part
				fi
			done
			IFS="${_ifs}"
			unset _ifs

			if test -z "${_found_module:-}" && test ! -z "${_server:-}"
			then
				_remote_url="${_server}${_dependency}"
				_found_module="${PWD}/${_dependency}"
				mkdir -p "$(dirname "${_found_module}")" 2>&1 >/dev/null
				if command -v workshop >/dev/null 2>&1
				then
					if command -v curl >/dev/null 2>&1
					then
						curl --fail -L "${_remote_url}" \
							2>/dev/null > "${_found_module}" ||
								_code=$?
					elif command -v wget >/dev/null 2>&1
					then
						wget -qO- "${_remote_url}" \
							2>/dev/null  > "${_found_module}" ||
								_code=$?
					else
						return 127
					fi

					_head=
					test ! -f "${_found_module}" ||
						_head="$(head -n1 "${_found_module}")"

					if test "${_head}" = "#!/usr/bin/env workshop" &&
						test "${_code:-0}" = 0 &&
						"${SHELL}" -n "${_found_module}" >/dev/null 2>&1
					then
						:
					else
						test ! -f "${_found_module}" ||
							rm "${_found_module}"
						return 1
					fi
				else
					return 127
				fi
			fi

			_required=''

			require ()
			{
				_required="${_required:-} ${*:-} "
			}

			"${SHELL}" -n "${_found_module}" >/dev/null 2>&1

			. "${_found_module}"

			_dependencies="${_required:-} ${_dependencies:-}"
			_modules="${_modules} ${_dependency} "
		done
	done

	set -- "${_main%%.*}" "${@:-}"

	workshop_path=${workshop_path:-${PWD}:${_executable_dir}}

	if test -z "${workshop_executable:-}"
	then
		workshop_executable="$(
			cd "${_executable_dir}";pwd
		)/$(
			basename "${_executable}"
		)"
	else
		workshop_executable="$(
			cd "$(dirname "${workshop_executable}")";pwd
		)/$(
			basename "${workshop_executable}"
		)"
	fi

	if test -z "${2:-}"
	then
		"${1:-}"
	else
		"${@:-}"
	fi
}

test -z "${1:-}" || workshop "${0}" "${@:-}"
